version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      MYSQL_PASSWORD: '${DBPASS}'
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
  opti_db:
    image: "mysql"
    container_name: opti_db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '${DBPASS}'
      MYSQL_ROOT_PASSWORD: 'verycomplexpassword'
